### ISSUE TITLE
DRAGON FRUITE DRAKE OVERSPAWN

### ISSUE THREAD

**Issue by Kajim573** [WolfShotz/Wyrmroost#93] opened 2020-09-08 02:33 UTC
The dragon fruite drake on my singleplayer world spawn in hundreds of dragons. Specifucly in the messa biome. I already try wiping them all with a kill command but they just re group in a matter of minutes...

**Comment by WolfShotz** [comment] 2020-09-08 02:35
Duplicate of #74

**Closed by WolfShotz** 2020-09-08 02:35 UTC
