### ISSUE TITLE
enigmatic legacy crash on world creation

### ISSUE THREAD

**Issue by imthekiduknowwhatimean** [WolfShotz/Wyrmroost#206] opened 2021-01-09 12:19 UTC
**Logs:** https://hastebin.com/poluzuriha.sql
**Crash report (this tamplate cringe)** https://hastebin.com/ipibeginip.properties

**Steps to Reproduce:**
 1. create a 1.16.4 forge 35.1.36 profile
 2. install enigmatic legacy 2.10.3 and wyrmroost 1.2.10
 3. start game and create world
 4. Behold!
 
**Description of issue:**
game crashes on world creation 
log and crashlog site an unamed lootpool that enigmatic legacy has handler specifically designed to detect 

(for anybody having that issue there is a option to dissable that handler specifically for crashes like this in the config file for enigmatic legacy, CrashOnUnnamedLootPool i think it's called)

**Comment by WolfShotz** [comment] 2021-01-09 18:48
Duplicate of #203

**Closed by WolfShotz** 2021-01-09 18:48 UTC
