### ISSUE TITLE
Game crashes when riding dragons

### ISSUE THREAD

**Issue by crosscutitan** [WolfShotz/Wyrmroost#211] opened 2021-01-12 22:02 UTC
**Steps to Reproduce:**
 1. put wyrmroost with create mod
 2. Then try and ride the dragons
 3. ...
When I ride a dragon for more than 2 minutes my game crashes I believe it it a compatibility error with create mod and the way it changes movement.
[crash-2021-01-12_16.55.11-client.txt](https://github.com/WolfShotz/Wyrmroost/files/5805037/crash-2021-01-12_16.55.11-client.txt)

**Comment by WolfShotz** [comment] 2021-01-12 22:25
Duplicate of #207 

This issue is on creates end, if you want updates take a look at the issue thread on create [here](https://github.com/Creators-of-Create/Create/issues/669)

**Closed by WolfShotz** 2021-01-12 22:25 UTC
