### ISSUE TITLE
[1.16.5] Server crash with Ticking Entity with The Abyss Chapter 2

### ISSUE THREAD

**Issue by MarioSMB** [WolfShotz/Wyrmroost#255] opened 2021-03-08 16:35 UTC
**Logs:**
[crash-2021-03-08_16.27.42-server.txt](https://github.com/WolfShotz/Wyrmroost/files/6102771/crash-2021-03-08_16.27.42-server.txt)

**Steps to Reproduce:**

**Description of issue:**
We were randomly exploring The Abyss chapter 2's dimension (which for some reason is full of dragons!), then the server crashed with a Ticking Entity error. Upon loading back in, the server crashed again, so it appears to be bricked at this stage.

**Comment by MarioSMB** [comment] 2021-03-08 17:06
Just an update, we were able to get around the crash by entering creative mode as soon as we logged in; the cause appears to be from multiple Royal Reds fighting in a close vicinity (their combat also appears to cause severe lag not unlike that of Fire & Ice).

**Comment by WolfShotz** [comment] 2021-04-03 21:02
This just seems like a duplicate of #122, the more I like at it.

**Closed by WolfShotz** 2021-04-03 21:02 UTC

**Comment by MarioSMB** [comment] 2021-04-03 21:42
That issue appears to be closed as well, does that mean this server crashing bug won't be addressed?

P.S. I've since removed The Abyss so the bug does not really concern me, my interest here is only for future users of these popular mods, as this repeated crashing was difficult to work around.

**Comment by WolfShotz** [comment] 2021-04-03 21:44
I pinged the wrong ONNNNE

**Comment by WolfShotz** [comment] 2021-04-03 21:44
There, fixed up

**Comment by MarioSMB** [comment] 2021-04-03 22:12
Ah, thanks for clearing that up!
