### ISSUE TITLE
[Wyrmroost-1.16.3-4-1.2.7] Too many mob spawned.

### ISSUE THREAD

**Issue by Daejangnamu** [WolfShotz/Wyrmroost#164] opened 2020-11-19 12:38 UTC
![unknown](https://user-images.githubusercontent.com/52635462/99667176-5b0aa600-2aaf-11eb-9242-e129f406432e.png)
![55555](https://user-images.githubusercontent.com/52635462/99667344-9c02ba80-2aaf-11eb-8775-98bedf3183ec.png)

![15555](https://user-images.githubusercontent.com/52635462/99695417-e34d7300-2ad0-11eb-85f9-db781910ce4d.png)

1. desertwyrm
2. dragon_fruit_drake

**Comment by WolfShotz** [comment] 2020-11-22 21:21
Duplicate of #147

**Closed by WolfShotz** 2020-11-22 21:21 UTC
