### ISSUE TITLE
tamed butterfly leviathans and royal reds still tries to kill me

### ISSUE THREAD

**Issue by BargerL216** [WolfShotz/Wyrmroost#259] opened 2021-03-10 19:32 UTC
I have this mod on a hosted server and so far taming alpines and silver gliders has been fine but when i tame a butterfly leviathan or a royal red even after taming they still kill me... please help. i worked hard for the royal red and i had to kill it.

**Comment by WolfShotz** [comment] 2021-03-20 04:16
Duplicate of #243

**Closed by WolfShotz** 2021-03-20 04:16 UTC
