### ISSUE TITLE
BUGGY DRAGON STAFF

### ISSUE THREAD

**Issue by KBOC359** [WolfShotz/Wyrmroost#173] opened 2020-12-01 06:29 UTC
it doesn't crash so i don't have a log to report, the screen freezes, for some reason i can still move and perform actions but the problem is i keep seing the same image with some weird textures, chests bed and stuff spammed on my screen, the only solution is alt f4, it happened in multiplayer ONLY when i used the dragon staff on a royal red to give him diamond armor.

**Comment by Volt-Six** [comment] 2020-12-02 01:29
I have the exact same problem in single player, but in my case it is whenever I have it selected in my hotbar, although it only started after I gave a Royal Red Dragon armour. Makes the staff completely unusable.

**Comment by WolfShotz** [comment] 2020-12-20 01:00
Duplicate of #176 (This may be the original issue but the other one has been acknowledged)

**Closed by WolfShotz** 2020-12-20 01:00 UTC
