### ISSUE TITLE
Butterfly Leviathan High Spawn Rate

### ISSUE THREAD

**Issue by vallay111** [WolfShotz/Wyrmroost#80] opened 2020-07-12 19:35 UTC
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

I have no logs, but I have some screenshots. The first one I literally just killed like 5 of them and left one, then another one spawned. The second one I didn't even touch yet.

![2020-07-12_12 28 28](https://user-images.githubusercontent.com/68201515/87255021-02116e00-c43c-11ea-8506-23d5381ff0fa.png)

![2020-07-12_12 28 55](https://user-images.githubusercontent.com/68201515/87255024-050c5e80-c43c-11ea-93af-9f069a1d23b5.png)

**Steps to Reproduce:**
 1. Live near an inlet of some sort
 2. Simply exist for a while
 3. Leviathans should start spawning like crazy

**Description of issue:**
There's just too many butterfly leviathans spawning. It drops my frames and mobs start doing that weird stutter step trying to move forward.

Edit: I also want to say that I am on wyrmroost 1.1.2 (aka 1.15.2 minecraft world) and I do have like 56 or 57 mods loaded in, but I only have a couple mods that add in a few mobs (Productive Bees mod, Rats mod, Dragon Mounts Legacy, Waddles, you know minor mob additions).

**Comment by mr-poyo** [comment] 2020-07-14 23:31
We also have high spawn rates on our server(1.15.2, custom pack). 

A config option for spawn chance/cap would be awesome. Or do they despawn? Perhaps allow ones that aren't named/tamed to despawn naturally.

**Comment by LagoonTheAbyssal** [comment] 2020-07-15 07:33
This error is known AND is going to (hopefully) be patched as of next release.
This is not fault of other mods or the sort, it is just Wyrmroost.
If you have issues with overspawning you can use 
> kill @e[type=wyrmroost:butterfly_leviathan,nbt={OwnerUUID:""}]

This will kill any untamed Butterfly Leviathans. If you'd like, you can test it in singleplayer to ensure it works. Works with any dragon :)

**Comment by WolfShotz** [comment] 2020-07-20 18:42
Duplicate of #74

**Closed by WolfShotz** 2020-07-20 18:42 UTC
