### ISSUE TITLE
1.15.2 Multiple player server crashed !

### ISSUE THREAD

**Issue by 27638166** [WolfShotz/Wyrmroost#191] opened 2020-12-24 16:29 UTC
Here is the crash report : https://pastebin.com/F8uCNQkq

**Steps to Reproduce:**
1. start server
2. crash :)

**Description of issue:**
I think it's pathfinder have some issue
And it need to be fix
Main problem : server tick over 60 seconds

**Comment by WolfShotz** [comment] 2020-12-25 21:22
Duplicate of #177

**Closed by WolfShotz** 2020-12-25 21:22 UTC
