### ISSUE TITLE
Entierly destroyes 1.16.3  worlds

### ISSUE THREAD

**Issue by TheJN101** [WolfShotz/Wyrmroost#128] opened 2020-10-26 11:34 UTC
played on a server with a friend, due the drake server crash attack we had to remove it until the fix drops.
after reentering the wyrmroost free server and leaving again later on we noticed the next day that the server was reset to the moment we removed wyrmroost. after many tries we had to restart the entire server from scratch.

later on the same thing happened to my singleplayer world every block changed since the removal of wyrmroost vanishes as soon as the world is closed. even if i just plant a tree its gone after i rejoin pls look into that worldeating drake

**Comment by WolfShotz** [comment] 2020-10-26 14:15
This sounds like a server provider issue than an issue with wyrmroost.. This crash would not affect the save of the world whatsoever. Regardless this is a duplicate of #119

**Closed** 2020-10-26 14:16 UTC

**Comment by TheJN101** [comment] 2020-10-26 14:23
thought so too but then it happened in a singelplayerworld too

**Comment by WolfShotz** [comment] 2020-10-26 14:24
Theyre called roll backs. This happens when the world doesn't save, so it goes back to when it was last saved. Because it crashed, it doesn't save, because it can't.

**Comment by TheJN101** [comment] 2020-10-26 18:20
but it cant even save after multiple restarts

**Comment by WolfShotz** [comment] 2020-10-26 18:24
.. your progress was lost.. theres no such thing as a "Roll Return"
When you dont save something and that something is closed, the progress is lost. Its like not saving a document your writing. A restart can't fix that.
