### ISSUE TITLE
My OW Drake's saddle disappears whenever I exit my world, and doesn't follow me when standing.

### ISSUE THREAD

**Issue by Makavo** [WolfShotz/Wyrmroost#88] opened 2020-07-23 21:59 UTC
The title says it all. And, when I make them stand, it doesn't walk to me, it just teleports.

How to reproduce (saddle disappearing)
1. Get any OW Drake.
2. Put a saddle on it.
3. Exit the world.
If you did it right, your Drake's saddle should be gone.

**Comment by WolfShotz** [comment] 2020-08-02 20:52
first of all, one issue per issue lmao
second, for ur first problem, yeah I did a dumb.
second problem is a duplicate of #87 maybe?

**Comment by WolfShotz** [comment] 2020-10-07 03:06
Fixed in 1.1.3

**Closed by WolfShotz** 2020-10-07 03:06 UTC
Labels: bug, fixed in-dev
