### ISSUE TITLE
Unknown Crash in Wyther's Volcano Biome

### ISSUE THREAD

**Issue by Spinogaming** [WolfShotz/Wyrmroost#136] opened 2020-11-10 07:27 UTC
When i am on the volcano biome from the WiIiam Wyther's datapack (replaces the mushroom island biome), i sometimes randomly crash
Crash report: https://pastebin.com/h2KtPFCj

**Comment by WolfShotz** [comment] 2020-11-10 13:17
reason, and duplicate of #137

**Closed by WolfShotz** 2020-11-10 13:17 UTC
