### ISSUE TITLE
Crash possibly related to Royal Red fire breath

### ISSUE THREAD

**Issue by Sniffity** [WolfShotz/Wyrmroost#168] opened 2020-11-22 19:38 UTC
Good day,

I recently experienced a crash upon using a Royal Red's "Fire Breath" ability. I had been able to use it without problems previously, but apparently using it continously on a pack of mobs generated the crash, for which I am attaching the appropiate crash report.  

[Crash Report - Dragon Fire Breath.txt](https://github.com/WolfShotz/Wyrmroost/files/5580164/Crash.Report.-.Dragon.Fire.Breath.txt)

Minecraft Version 1.16.3
Forge Version 34.1.42
OptiFine Version 1.16.3_HD_U_G5 (in case it is necessary).

I hope this helps,

Regards,

-Sniffity

**Comment by WolfShotz** [comment] 2020-11-22 21:23
Duplicate of #163

**Closed by WolfShotz** 2020-11-22 21:23 UTC
