### ISSUE TITLE
[Wyrmroost-1.16.3-1.2.7] Sever crash

### ISSUE THREAD

**Issue by Daejangnamu** [WolfShotz/Wyrmroost#192] opened 2020-12-25 17:35 UTC
[crash-2020-12-25_19.14.31-server.txt](https://github.com/WolfShotz/Wyrmroost/files/5742234/crash-2020-12-25_19.14.31-server.txt)

Cannot reproduce T_T

forge-1.16.4-35.1.12

**Comment by WolfShotz** [comment] 2020-12-25 21:22
Duplicate of #177

**Closed by WolfShotz** 2020-12-25 21:22 UTC
