### ISSUE TITLE
Alpines Don't Breed

### ISSUE THREAD

**Issue by Syrikal** [WolfShotz/Wyrmroost#263] opened 2021-03-12 14:08 UTC
**Steps to Reproduce:**
 1. Tame two alpines
 2. Feed them honey or honeycomb
 3. Observe

**Description of issue:**
I have a pair of alpines. When I feed them honey or honeycomb to initiate breeding, they'll each make heart particles, but they won't pathfind to each other (no they're not sitting), and even when they do get close by random wandering they don't produce an egg. This happened starting with the first time I tried to breed them.

**Comment by WolfShotz** [comment] 2021-03-20 04:18
Duplicate of #230

**Closed by WolfShotz** 2021-03-20 04:18 UTC
