### ISSUE TITLE
Royal Red Dragon VS Ender Dragon apparent pathfinding issue

### ISSUE THREAD

**Issue by CodySpirits** [WolfShotz/Wyrmroost#210] opened 2021-01-12 16:52 UTC
**Steps to Reproduce:**
 1. Bring a tamed Royal Red Dragon (Dragon was female, though I doubt that matters too much here) into the End via an End Portal.
 2. Attack the Ender Dragon or be attacked by the Ender Dragon to get the Royal Red to turn aggressive towards the Ender Dragon
 3. Wait until the Ender Dragon flies directly through an Obsidian Pillar.

**Description of issue:**

The Royal Red will pursue the Ender Dragon (notably, it doesn't appear to do any sort of damage). If the Ender Dragon flies into one of the Obsidian Pillars of the End Island and is going through the blocks of the pillar, it will cause an immense amount of lag as the Royal Red Dragon pursues the Ender Dragon. This behavior appears to be due to the Royal Red dragon attempting to pathfind to the Ender Dragon and being unable to, as the Ender Dragon is inside of blocks. I've also provided a crash report as well. It should also be noted that this took place in a server with a long list of other mods present rather than on a single client side in an isolated situation. I'm submitting this with the belief that none of the present mods were able to cause the related issue.

**Crash Report:** https://pastebin.com/J46jxJyr

**Comment by Spinogaming** [comment] 2021-01-12 17:22
First, the ender dragon can only be damaged by explosions and the player. Second, this issue also happens with players, if a player hides behind a wall or under a tree, a huge amount of lag occurs

**Comment by WolfShotz** [comment] 2021-01-12 20:37
These all appear to be related go vanilla issues.
And if it isn't, its just the RR having trouble to pathfind in general, and is such this issue is a duplicate of #177

**Closed by WolfShotz** 2021-01-12 20:37 UTC
Labels: vanilla bug, wontfix
