### ISSUE TITLE
[1.14.4] Ticking Entity - Server Crash

### ISSUE THREAD

**Issue by Gbergz** [WolfShotz/Wyrmroost#48] opened 2020-01-31 11:39 UTC
**Crash-report:** https://gist.github.com/Gbergz/881591e857c0df57684b2f1896d3d6a4

**Steps to Reproduce:**
 1. Server on
 2. Wait for the entity to load in
 3. Crash.
 4. Profit.

**Description of issue:**
Stuck in a crash-loop when the player is close to the "crashing" entity.

**Other Info:**

**Forge**: 28.1.107
**Minecraft**: 1.14.4
**Mod Version**: 1.02

**Comment by Kingdomall** [comment] 2020-01-31 11:53
this issue is most likely caused by forge or another mod.
I noticed that you use Forge .107, which is not recommended. Please attempt to use recommended Forge. If you can't because a mod requires it and/or crashes on recommended, I apologize in advance if that's the problem. I noticed that you are using a lot of mods, and that could honestly trigger the problem.
To clarify what the problem could be, I hypothesize that a mod's chest (say an iron chest) could be conflicting with the roost stalker, which is designed to take things out of storage blocks like chests.
There are many things that could trigger the roost stalker's motives to respond null; for now I hope these solve your problem for now.
Regardless of the outcome, thank you for reporting. This bug will be patched as soon as possible for the next big update.
(Our coder WolfShotz may reply later on with a clearer answer, I just wanted to see if I could help you in some way)

**Comment by WolfShotz** [comment] 2020-01-31 11:57
tis a dupe, fixed in dev 😛

**Closed by WolfShotz** 2020-01-31 11:57 UTC
Labels: duplicate

**Comment by WolfShotz** [comment] 2020-01-31 11:59
Alternatively u may want to give `/kill @e[type=wyrmroost:rooststalker]` a try once u approach the affected area. Can’t guarantee this will work tho, and if it doesnt u may need to remove the entity yourself in an NBT editor of sort.
