### ISSUE TITLE
Drakes losing saddles

### ISSUE THREAD

**Issue by Dragonmatic** [WolfShotz/Wyrmroost#62] opened 2020-05-14 15:15 UTC
After taming an overworld drake and trying to access it's inventory with the dragon staff, the saddle no longer exists. (Have encountered the issue only on multiplayer)

**Comment by WolfShotz** [comment] 2020-05-14 21:42
dragon u moron check closed issues

Duplicate of #60

**Closed by WolfShotz** 2020-05-14 21:42 UTC
