### ISSUE TITLE
ridingPerspective 121 Fired  [any insight]

### ISSUE THREAD

**Issue by frakier** [WolfShotz/Wyrmroost#50] opened 2020-02-26 02:04 UTC
Any insight into this, is this like the mob being ridden problem.

[WolfShotz.Wyrmroost.event.EventHandler$Client:ridingPerspective:121]: Fired

In log 300,000 times

This happens on logging into a existing world, been playing for awhile [months] with no problems.
Two time outs when trying to log in today. Have to stop the server and reload to get in.
Too many mods to test in batches over long periods of game play so figured I would ask for any insight before I forcefully excised the mod.

Wyrmroost-1.14.4-1.0.2.jar
forge-1.14.4-28.1.114

and a list of other mods..

**Comment by WolfShotz** [comment] 2020-02-26 02:06
Duplicate of #46 

This was my fault, this feature from forge was not functioning at the time of this wyrmroost release and I had completely forget about the logging for it. It will be fixed next version.

**Comment by frakier** [comment] 2020-02-26 02:14
So it would not be the reason I cannot log in then?

**Comment by WolfShotz** [comment] 2020-02-26 02:15
Not being able to login has *nothing* to do with this issue or our mod. If you still think otherwise, you should provide a log and I will re-open this issue.

**Closed by WolfShotz** 2020-02-26 02:15 UTC
Labels: duplicate

**Comment by frakier** [comment] 2020-02-26 02:20
Thanks I figured that was what you were saying just wanted to verify, I'll have to keep digging.
