### ISSUE TITLE
I was AFK and I crashed

### ISSUE THREAD

**Issue by CodaBear1552** [WolfShotz/Wyrmroost#9] opened 2019-09-23 10:56 UTC
I'm not sure what happened, I believe it's being caused by Wyrmroost, but I'm not positive.

I was afk, after spawning in many, many dragons and when I came back I had crashed.
[https://pastebin.com/E15ez5Cx](url)

**Comment by WolfShotz** [comment] 2019-09-23 11:02
Duplicate of #8

**Closed by WolfShotz** 2019-09-23 11:02 UTC
