### ISSUE TITLE
Alpine Takes Fall Damage With Passable Foliage

### ISSUE THREAD

**Issue by aluunzui** [WolfShotz/Wyrmroost#257] opened 2021-03-10 02:00 UTC
**Steps to Reproduce:**
 1. install passable foliage mod
 2. fly alpine down into leaves
 3. ...

Usually when flying an alpine they don't really take fall damage but with passable foliage they will take an impressive amount of damage and i feel like its a very needed mod if you want to ride anything that doesn't fly in Wyrmroost

Example:
https://youtu.be/Vstxcq7rYdk

**Comment by WolfShotz** [comment] 2021-03-10 04:01
Duplicate of #235

**Closed by WolfShotz** 2021-03-10 04:01 UTC
