### ISSUE TITLE
Tames randomly getting deleted

### ISSUE THREAD

**Issue by DebonairDoug** [WolfShotz/Wyrmroost#193] opened 2020-12-25 21:19 UTC
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**

**Comment by WolfShotz** [comment] 2020-12-25 21:22
Duplicate of #188

**Closed by WolfShotz** 2020-12-25 21:22 UTC
