### ISSUE TITLE
[1.15.2] Lesser Desertwyrm overpopulation issue

### ISSUE THREAD

**Issue by GalacticRuler** [WolfShotz/Wyrmroost#92] opened 2020-07-31 22:44 UTC
**Logs:** - N/A -
**Steps to Reproduce:**
 1. Generate a new world and seek out a desert

**Description of issue:** Lesser Desertwyrms are *massively* over spawning.

**Comment by WolfShotz** [comment] 2020-07-31 22:44
Duplicate of #74

**Closed by WolfShotz** 2020-07-31 22:44 UTC
