### ISSUE TITLE
INVISIBLE DRAGON?!?!

### ISSUE THREAD

**Issue by internetorian** [WolfShotz/Wyrmroost#231] opened 2021-02-10 19:35 UTC
**Steps to Reproduce:**
 1. die while riding the dragon
 2. respawn out of range of teleport
 3. walk close enough for it to teleport again

Description of issue:
when i die and spawn out of range of the dragon, when it teleports back to me it goes invisible and doesnt come back until the server im playing on is restarted

**Comment by WolfShotz** [comment] 2021-02-10 19:45
Duplicate of #229

**Closed by WolfShotz** 2021-02-10 19:45 UTC
