### ISSUE TITLE
Silver Glider + Riding a Drake = Crash instead of Glider Dismount

### ISSUE THREAD

**Issue by LagoonTheAbyssal** [WolfShotz/Wyrmroost#15] opened 2019-09-24 22:00 UTC
Reported by AotuurLe.
https://pastebin.com/t4KPC5z6

**Comment by WolfShotz** [comment] 2019-09-25 01:32
Elaborate.

**Comment by WolfShotz** [comment] 2019-09-25 03:48
ok good catch, was able to reproduce. Thank u for the report.

**Comment by WolfShotz** [comment] 2019-09-26 02:25
Turns out to be a duplicate of #13. Closing

**Closed by WolfShotz** 2019-09-26 02:25 UTC
Labels: bug
