### ISSUE TITLE
Flying Creatures - "Flying while sleeping" / Stuck in a sleep pose when riding them

### ISSUE THREAD

**Issue by Sniffity** [WolfShotz/Wyrmroost#189] opened 2020-12-23 07:51 UTC
**Steps to Reproduce:**
 1. Tame a Royal Red
 2. Set time to night.
 3. Place tamed Royal Red inside a Dragon Soul Crystal
 4. Release Royal Red from Dragon Soul Crystal.
 5. Immediately, as it's doing the animation to fall asleep, mount the Royal Red.
 6. Royal Red will basically "fly while sleeping". It will be unable to turn to the sides. Upon dismounting it, you will be unable to issue the sit command by shift right-clicking it.

**Description of issue:**
Royal Reds (and Alpines too) sometimes get stuck in a "sleeping position" upon being mounted, being unable to turn around. When this happens, they can onle be flown backwards and forwards in a straight line, their head will be tilted to the side. The steps to reproduce above, I have found, are one way to recreate the bug, but this will also occurr randomly when mounting sleeping Royal Reds and Alpines. 

**Possibly** related to closed Issue #159 and Issue #140.

**Comment by Sniffity** [comment] 2020-12-23 07:53
Screenshot of issue occurring (forgot to add above, apologies). Notice the Royal Red's head tilted to the side, stuck in a sleeping pose. Wings will not move either.
![image](https://user-images.githubusercontent.com/66455728/102972961-f2f21a00-44c9-11eb-9c00-f582f492b9b8.png)

Easiest way to reproduce is to set time specifically to 20,000 and allow the Royal Red to fall asleep before getting it inside the Dragon Soul Crystal.

**Comment by MaliceUlog** [comment] 2021-01-05 11:24
A player on the server I'm on is having this same exact issue with his Alpine Dragon. Was there ever a solution to this?

**Comment by WolfShotz** [comment] 2021-01-05 13:26
The issue's been resolved in-dev so I can't count it as resolved until release, but there are solutions currently.
The issue is all revolved around sleeping, if you can get it to wake up before interacting with it, then everything should work fine.

**Closed** 2021-01-19 01:09 UTC
Labels: bug, fixed
