### ISSUE TITLE
video with many broken drake glitches 0-0

### ISSUE THREAD

**Issue by Robomnz** [WolfShotz/Wyrmroost#84] opened 2020-07-18 04:55 UTC
ok glitch list
1. is drakes standing/sitting when not told to
2. drakes nearby copying what you do to one drake
3. pretty sure your already aware of vibrating issue
4. drakes laying down (partially) while being ridden
5. Drake and other dragon inventories not opening when using the staff and clicking open inventory (not shown)

https://www.youtube.com/watch?v=QNFgO8uLqek&feature=youtu.be

**Comment by WolfShotz** [comment] 2020-07-20 18:40
Duplicate of #73

**Closed by WolfShotz** 2020-07-20 18:40 UTC
